# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='photos/')),
                ('name', models.CharField(max_length=40)),
                ('descri', models.TextField(max_length=6000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Category')),
                ('loca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Location')),
            ],
        ),
    ]
