# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='loca',
        ),
        migrations.AddField(
            model_name='photos',
            name='loca',
            field=models.ManyToManyField(to='personal.Location'),
        ),
    ]
